apiVersion: v1
kind: Service
metadata:
  labels:
    app: todomvc
    visualize: "true"
  name: todomvc
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: todomvc
  type: NodePort
