apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        db: redis-todomvc
        visualize: "true"
    spec:
      containers:
      - name: redis-todomvc
        image: hypriot/rpi-redis
        ports:
        - containerPort: 6379
