apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todomvc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todomvc
        visualize: "true"
    spec:
      containers:
      - name: todomvc
        image: jbclaramonte/todomvc-springboot:kube-redis-arm
        ports:
        - containerPort: 8080
